### ISSUE TITLE
panic and more miss

### ISSUE THREAD

**Issue by beaquant** [yireyun/go-queue#15]
Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz   2.11 GHz
8.00 GB (7.76 GB 可用)
Windows 10 家庭中文版
```
PS D:\temp\go-queue> go test -race        
go1.17.8, Grp:   1, Times:    1000000, miss:  2276, use:   4.2984884s,  4.298µs/op
go1.17.8, Grp:   2, Times:    2000000, miss: 14993, use:  14.5299581s,  7.264µs/op
go1.17.8, Grp:   3, Times:    3000000, miss: 33229, use:  24.6319776s,   8.21µs/op
go1.17.8, Grp:   4, Times:    4000000, miss: 50272, use:  19.9088221s,  4.977µs/op
go1.17.8, Grp:   5, Times:    5000000, miss: 87873, use:  27.8026844s,   5.56µs/op
go1.17.8, Grp:   6, Times:    6000000, miss:131258, use:  32.7322928s,  5.455µs/op
go1.17.8, Grp:   7, Times:    7000000, miss:223056, use:  46.5430837s,  6.649µs/op
panic: test timed out after 10m0s

goroutine 1171 [running]:
testing.(*M).startAlarm.func1()
        D:/APP/go/src/testing/testing.go:1788 +0xbb
created by time.goFunc
        D:/APP/go/src/time/sleep.go:180 +0x4a

goroutine 1 [chan receive, 8 minutes]:
testing.(*T).Run(0xc0001051e0, {0x2b043d, 0x10}, 0x2b9978)
        D:/APP/go/src/testing/testing.go:1307 +0x752
testing.runTests.func1(0x0)
        D:/APP/go/src/testing/testing.go:1598 +0x9a
testing.tRunner(0xc0001051e0, 0xc000143bf8)
        D:/APP/go/src/testing/testing.go:1259 +0x230
testing.runTests(0xc00016e000, {0x3d8da0, 0x6, 0x6}, {0x0, 0x1b376daffff, 0x3dcbc0})
        D:/APP/go/src/testing/testing.go:1596 +0x7cb
testing.(*M).Run(0xc00016e000)
        D:/APP/go/src/testing/testing.go:1504 +0x9d2
main.main()
        _testmain.go:53 +0x22c

goroutine 687 [semacquire, 6 minutes]:
sync.runtime_Semacquire(0xc0011f2db4)
        D:/APP/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc0011f2db4)
        D:/APP/go/src/sync/waitgroup.go:130 +0xf1
_/D_/temp/go-queue.testQueueGeneral(0xc000a5ba00, 0x8, 0xf4240)
        D:/temp/go-queue/esQueue_test.go:227 +0x545
_/D_/temp/go-queue.TestQueueGeneral(0x0)
        D:/temp/go-queue/esQueue_test.go:74 +0x285
testing.tRunner(0xc000a5ba00, 0x2b9978)
        D:/APP/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
        D:/APP/go/src/testing/testing.go:1306 +0x727

goroutine 1155 [runnable]:
runtime.Gosched()
        D:/APP/go/src/runtime/proc.go:322 +0x1a
_/D_/temp/go-queue.(*EsQueue).Get(0xc0001385d0)
        D:/temp/go-queue/esQueue.go:195 +0x125
_/D_/temp/go-queue.testQueueGeneral.func2(0x0)
        D:/temp/go-queue/esQueue_test.go:217 +0x105
created by _/D_/temp/go-queue.testQueueGeneral
        D:/temp/go-queue/esQueue_test.go:213 +0x330

goroutine 1105 [sleep]:
time.Sleep(0x3e8)
        D:/APP/go/src/runtime/time.go:193 +0x133
_/D_/temp/go-queue.testQueueGeneral.func1(0x0)
        D:/temp/go-queue/esQueue_test.go:204 +0x251
created by _/D_/temp/go-queue.testQueueGeneral
        D:/temp/go-queue/esQueue_test.go:198 +0x129
exit status 2
FAIL    _/D_/temp/go-queue      600.799s
```

**Comment by yireyun** [comment]
这个是测试超时了，Golang的测试时间最长是10分钟，超时就抛异常

```
panic: test timed out after 10m0s
```
